-- USER SQL
CREATE USER starbook IDENTIFIED BY "1234"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO starbook ;
GRANT "RESOURCE" TO starbook ;
ALTER USER starbook DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES

